[[content]]
asset = "SSA2"
type = "primary"
data = "ਸਭੁ ਆਪੇ ਆਪਿ ਵਰਤਦਾ; ਆਪੇ ਭਰਮਾਇਆ ॥"
page = 229
line = 9

[[content]]
asset = "SBMS"
type = "translation"
language = "en"
data = "By Himself, the Lord pervades ever-where and Himself He strays the mortals."

[[content]]
asset = "SBMS"
type = "translation"
language = "pa"
data = "ਖ਼ੁਦ-ਬ-ਖ਼ੁਦ ਹੀ ਸਾਹਿਬ ਸਾਰੇ ਵਿਆਪਕ ਹੋ ਰਿਹਾ ਹੈ ਤੇ ਉਹ ਖ਼ੁਦ ਹੀ ਪ੍ਰਾਣੀਆਂ ਨੂੰ ਕੁਰਾਹੇ ਭਟਕਾਉਂਦਾ ਹੈ।"

[[content]]
asset = "DSSK"
type = "translation"
language = "en"
data = "He Himself is All-pervading; He Himself misleads the people."

[[content]]
asset = "NKFT"
type = "translation"
language = "pa"
data = "ਸਰਬ ਰੂਪ ਹੋ ਕਰ ਆਪ ਹੀ ਆਪ ਵਰਤ ਰਹਾ ਹੈ, ਆਪ ਹੀ ਅਗ੍ਯਾਨੀਓਂ ਕੋ ਪ੍ਰਪੰਚ ਮੇਂ ਭਰਮਾਇ ਦੀਆ ਹੈ॥"

[[content]]
asset = "PSST"
type = "translation"
language = "pa"
data = "(ਪਰ ਮਾਇਆ ਵਿਚ ਤੇ ਜੀਵਾਂ ਵਿਚ) ਸਭ ਥਾਂ ਪਰਮਾਤਮਾ ਆਪ ਹੀ ਆਪ ਵਿਆਪਕ ਹੈ, ਆਪ ਹੀ ਜੀਵਾਂ ਨੂੰ ਕੁਰਾਹੇ ਪਾਂਦਾ ਹੈ।"

[[content]]
asset = "PSST"
type = "note"
language = "pa"
data = "ਸਭੁ = ਹਰ ਥਾਂ। ਆਪੇ = (ਪ੍ਰਭੂ) ਆਪ ਹੀ। ਭਰਮਾਇਆ = ਭੁਲੇਖੇ ਵਿਚ ਪਾਇਆ।"

[[content]]
asset = "SNST"
type = "translation"
language = "es"
data = "El Señor Mismo hace todo; Dios Mismo nos desvía del Sendero."