[[content]]
asset = "DGDG"
type = "primary"
data = "ਹੋ ਚਿਮਟਿ ਚਿਮਟਿ ਤਿਹ ਭਜਿਯੋ; ਹਰਖ ਉਪਜਾਇ ਕੈ ॥੨੫॥"
page = 1044

[[content]]
asset = "RSJD"
type = "translation"
language = "pa"
data = "ਅਤੇ ਪ੍ਰਸੰਨਤਾ ਪੂਰਵਕ ਚਿਮਟ ਚਿਮਟ ਕੇ ਉਸ ਨਾਲ ਰਤੀ-ਕ੍ਰੀੜਾ ਕੀਤੀ ॥੨੫॥"