[[content]]
asset = "SSA2"
type = "primary"
data = "ਹਰਿ ਇਕਸੈ ਦੀ. ਮੈ ਟੇਕ ਹੈ; ਜੋ ਸਿਰਿ ਸਭਨਾ ਸਮਰਥੁ ॥"
page = 958
line = 19

[[content]]
asset = "SBMS"
type = "translation"
language = "en"
data = "I have the support of the one Lord, who is omnipotent over the heads of all."

[[content]]
asset = "SBMS"
type = "translation"
language = "pa"
data = "ਮੈਨੂੰ ਇਕ ਪ੍ਰਭੂ ਦਾ ਹੀ ਆਸਰਾ ਹੈ ਜੋ ਸਾਰਿਆਂ ਦੇ ਸੀਸਾਂ ਉਤੇ ਸਰਬ ਸ਼ਕਤੀਵਾਨ ਹੈ।"

[[content]]
asset = "DSSK"
type = "translation"
language = "en"
data = "I take the Support of the One Lord alone; He is all-powerful, over the heads of all."

[[content]]
asset = "NKFT"
type = "translation"
language = "pa"
data = "ਇਕ ਹਰੀ ਕੀ ਹੀ ਮੁਝ ਕੋ ਓਟ ਹੈ, ਜੋ ਸਭ ਕੇ ਸਿਰ ਪਰ ਸਾਮਰਥ ਹੈ॥"

[[content]]
asset = "PSST"
type = "translation"
language = "pa"
data = "ਜੋ ਪਰਮਾਤਮਾ ਸਭ ਜੀਵਾਂ ਦੇ ਸਿਰ ਉਤੇ ਬਲੀ ਹੈ ਮੈਨੂੰ ਕੇਵਲ ਉਸੇ ਦਾ ਹੀ ਆਸਰਾ ਹੈ।"

[[content]]
asset = "SNST"
type = "translation"
language = "es"
data = "Mi Señor es Benévolo conmigo, Él bendice a los benefactores de la Tierra."