[[content]]
asset = "SSA2"
type = "primary"
data = "ਕਾਲੁ ਨ ਛੋਡੈ; ਬਿਨੁ ਸਤਿਗੁਰ ਕੀ ਧੀਰਾ ॥੭॥"
page = 227
line = 9

[[content]]
asset = "SBMS"
type = "translation"
language = "en"
data = "Death spares them not without the support of the True Guru."

[[content]]
asset = "SBMS"
type = "translation"
language = "pa"
data = "ਸੱਚੇ ਗੁਰਾਂ ਦੇ ਆਸਰੇ ਬਗੈਰ ਮੌਤ ਉਨ੍ਹਾਂ ਨੂੰ ਨਹੀਂ ਛਡਦੀ।"

[[content]]
asset = "DSSK"
type = "translation"
language = "en"
data = "Death does not spare them, without the Support of the True Guru. ||7||"

[[content]]
asset = "NKFT"
type = "translation"
language = "pa"
data = "ਸਤਿਗੁਰੋਂ ਕੀ ਧੀਰਜਤਾ ਦੀਏ ਬਿਨਾ ਕਾਲੁ ਨਹੀਂ ਛੋਡਤਾ ਹੈ॥੭॥"

[[content]]
asset = "PSST"
type = "translation"
language = "pa"
data = "ਤਾਂ ਮੌਤ ਖ਼ਲਾਸੀ ਨਹੀਂ ਕਰਦੀ (ਆਤਮਕ ਮੌਤ ਖ਼ਲਾਸੀ ਨਹੀਂ ਕਰਦੀ, ਆਤਮਕ ਜੀਵਨ ਪਲਰਦਾ ਨਹੀਂ)। ਸਤਿਗੁਰੂ ਤੋਂ ਮਿਲੇ (ਨਾਮ-) ਆਧਾਰ ਤੋਂ ਬਿਨਾ (ਇਹ ਆਤਮਕ ਮੌਤ ਟਿਕੀ ਹੀ ਰਹਿੰਦੀ ਹੈ) ॥੭॥"

[[content]]
asset = "SNST"
type = "translation"
language = "es"
data = "y sin el apoyo del Guru, son perseguidos siempre por la muerte. (7)"